---

# tasks file for systemd-timesyncd/tests

- name:  Get timedatectl status
  shell: timedatectl status
  register: timedatectl_status
  changed_when:  False
  failed_when: False
  tags:
    - test
    - assert

- name:  Get timedatectl timesync-status
  shell: timedatectl timesync-status
  register: timedatectl_timesync_status
  changed_when:  False
  failed_when: False
  tags:
    - test
    - assert

- name:  Get systemctl status systemd-timesyncd
  shell: systemctl status systemd-timesyncd
  register: timesyncd_status
  changed_when:  False
  failed_when: False
  tags:
    - test
    - assert

- name: Assert systemd-timesyncd status
  assert:
    that: 'timesyncd_status.stdout | regex_search("{{ item.regex }}")'
    msg:  '{{ item.fail_msg }}'
  with_items:

    - regex:    'Active:.*running'
      fail_msg: 'systemd-timesyncd does not appear to be running'

    - regex:    'Started Network Time Synchronization'
      fail_msg: 'systemd-timesyncd does not appear to have started NTP Synchronization'

  tags:
    - test
    - assert

- name: Assert timedatectl status
  assert:
    that: 'timedatectl_status.stdout | regex_search("{{ item.regex }}")'
    msg:  '{{ item.fail_msg }}'
  with_items:

    - regex:    'synchronized: yes'
      fail_msg: 'timedatectl status does not report timesyncd as NTP synchronized'

    - regex:    'Time zone: {{ default.timezone }}'
      fail_msg: 'timedatectl status expects timezone to be {{ default.timezone }}'

  tags:
    - test
    - assert

# Note: systemd >= 242 only
- name: Assert timedatectl timesync-status
  assert:
    that: 'timedatectl_timesync_status.stdout | regex_search("{{ item.regex }}")'
    msg:  '{{ item.fail_msg }}'
  when:
    timedatectl_timesync_status.rc == 0
  with_items:

    - regex:    'Server. \d+'
      fail_msg: 'timesyncd status does not report synchronizing with a server'

    - regex:    'Stratum. \d+'
      fail_msg: 'timesyncd status does not report stratum of server'

    - regex:    'Poll interval. \d+'
      fail_msg: 'timesyncd status does not report ntp poll interval'

    - regex:    'Delay: \d+'
      fail_msg: 'timesyncd status does not report NTP delay'

  tags:
    - test
    - assert

